<?php

namespace AppBundle\Repository;

/**
 * kaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class kaleRepository extends \Doctrine\ORM\EntityRepository
{
}
