<?php

namespace AppBundle\Repository;

/**
 * PersonCompanyRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonCompanyRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
