<?php

namespace AppBundle\Repository;

/**
 * PersonCompanyRoleJoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonCompanyRoleJoinRepository extends \Doctrine\ORM\EntityRepository
{
}
