<?php

namespace AppBundle\Repository;

/**
 * projectStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class projectStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
